# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-projects',
                'doc_host': 'https://GoldFish88.github.io',
                'git_url': 'https://github.com/GoldFish88/data-projects',
                'lib_path': 'data_project'},
  'syms': { 'data_project.energyforecast': { 'data_project.energyforecast.aemo_price_demand': ( 'energyforecast.html#aemo_price_demand',
                                                                                                'data_project/energyforecast.py')}}}
